import 'package:flutter/material.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:gap/gap.dart';
import 'package:inshorts/core/core.dart';
import 'package:inshorts/data/preference/preference.dart';
import 'package:inshorts/generated/assets.gen.dart';
import 'package:inshorts/resources/resources.dart';
import 'package:inshorts/ui/dashboard/dashboard.dart';
import 'package:inshorts/ui/login/login.dart';
import 'package:inshorts/ui/onboarding/onboarding.dart';
import 'package:inshorts/ui/read_news/read_news.dart';
import 'package:inshorts/utils/ad/ads.dart';
import 'package:network/helper/logger.dart';
import 'package:network/network.dart';
import 'package:provider/provider.dart';
import 'package:timezone/data/latest_all.dart' as tz;
import 'package:timezone/timezone.dart' as tz;

part 'splash_screen.dart';
part 'splash_provider.dart';