// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU0Avut9CQeOwKmlVj3hR0KuzHNUnvgOw',
    appId: '1:832096127020:web:515da6f728b90f1378a989',
    messagingSenderId: '832096127020',
    projectId: 'inshorts-c9418',
    authDomain: 'inshorts-c9418.firebaseapp.com',
    storageBucket: 'inshorts-c9418.firebasestorage.app',
    measurementId: 'G-2L0TYNW8SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5QK9lHds9C6DDA9Fpyb7Pw8t_fpksSI',
    appId: '1:832096127020:android:7e98240a8bf8224878a989',
    messagingSenderId: '832096127020',
    projectId: 'inshorts-c9418',
    storageBucket: 'inshorts-c9418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJsdiRTyBN2ZF6IQ0OwewdqMkd49zcg0',
    appId: '1:832096127020:ios:9a09afa60270d1fd78a989',
    messagingSenderId: '832096127020',
    projectId: 'inshorts-c9418',
    storageBucket: 'inshorts-c9418.firebasestorage.app',
    iosBundleId: 'com.makemonefromnews.makemoneyfromreadingnews.dailynews.newsread.earnmoney.breakingnewsdaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJsdiRTyBN2ZF6IQ0OwewdqMkd49zcg0',
    appId: '1:832096127020:ios:9a09afa60270d1fd78a989',
    messagingSenderId: '832096127020',
    projectId: 'inshorts-c9418',
    storageBucket: 'inshorts-c9418.firebasestorage.app',
    iosBundleId: 'com.makemonefromnews.makemoneyfromreadingnews.dailynews.newsread.earnmoney.breakingnewsdaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU0Avut9CQeOwKmlVj3hR0KuzHNUnvgOw',
    appId: '1:832096127020:web:e26d8f33d43d4d9778a989',
    messagingSenderId: '832096127020',
    projectId: 'inshorts-c9418',
    authDomain: 'inshorts-c9418.firebaseapp.com',
    storageBucket: 'inshorts-c9418.firebasestorage.app',
    measurementId: 'G-2GK16CV4E0',
  );
}
